### ISSUE TITLE
Test and potentially add support for AWS RDS

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [cyralinc/approzium#120]
This issue is to test whether our current Postgres implementation will connect to [Amazon RDS](https://aws.amazon.com/rds/postgresql/), which is a commonly-used Amazon-hosted Postgres database. If it does, we're done. If not, we should try to add support.

**Steps**

- Create an RDS instance for testing inside a Cyral-paid Amazon account
- Create a username and password
- Run the authenticator locally
- Run the Python client locally
- Attempt to retrieve a connection to the database using the Python client

This could be completed either inside the Docker dev environment, or outside of it.

**Comment by UpGado** [comment]
Tested and works! ✅ 

- Followed steps as stated.
- Tested on both Mac and Docker dev environment.

**Comment by tyrannosaurus-becks** [comment]
That is awesome, @UpGado ! For RDS, are the connection strings exactly the same? Or is there any difference?

**Comment by UpGado** [comment]
> That is awesome, @UpGado ! For RDS, are the connection strings exactly the same? Or is there any difference?

They are the same. This is what it looked like, for example:
```python
conn = connect(host='rds-dbpg.*******.us-east-2.rds.amazonaws.com',
               user='bob', authenticator=auth,
               dbname='finance')
```

**Comment by tyrannosaurus-becks** [comment]
That is awesome! If it's the same, I'm not sure if it would be valuable to add an example for it. Do you think we should add an example somewhere with a note that we do support Amazon RDS? Or do you think it's implied so it's better to just leave it off?

**Comment by UpGado** [comment]
I lean towards leaving it off, since RDS claims to be Postgres compatible, it should be implied.

**Comment by tyrannosaurus-becks** [comment]
I think we're done then! Thanks for testing!
