### ISSUE TITLE
Point approzium.com docs at main branch

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [cyralinc/approzium#186]
This issue is to point the approzium.com docs at the main branch, so they'll get deployed at the same time as releases. Presently they're pointed at develop, so sometimes docs go up for unreleased changes.

**Comment by timothydnguyen** [comment]
Just updated our netlify settings to so approzium.com is based on our main branch. we should still get previews for PRs to `main` and `develop`. Thanks for reminding me!

**Comment by tyrannosaurus-becks** [comment]
Thank you for doing that! Looks really good!
