### ISSUE TITLE
Implement TLS on authenticator server and client SDK

### ISSUE THREAD

**Issue by UpGado** [cyralinc/approzium#67]

**Comment by tyrannosaurus-becks** [comment]
FWIW, [here](https://www.vaultproject.io/docs/configuration/listener/tcp) is the TLS config exposed by Vault. Not that we need to do it the same way, just as a reference for deciding what we want to do.

**Comment by tyrannosaurus-becks** [comment]
I've found a very helpful guide here: https://itnext.io/practical-guide-to-securing-grpc-connections-with-go-and-tls-part-1-f63058e9d6d1

Also, there are some of these elements located in an example config [here](https://www.vaultproject.io/docs/configuration/listener/tcp).

**Comment by tyrannosaurus-becks** [comment]
I've assigned this to myself because in order to check whether the GRPC server is healthy, I'll need to implement this.
