### ISSUE TITLE
pg auth blogpost

### ISSUE THREAD

**Issue by timothydnguyen** [cyralinc/approzium#9]
tim - define outline, get necessary info from dio

**Comment by timothydnguyen** [comment]
it seems like our original topic of merely defining the various password auth methods has been recently written elsewhere.

To avoid regurgitating the information, we'd like to take the angle of why SCRAM is more secure and therefor preferred, then understand why the less secure md5 is the default over SCRAM for postgres (performance?)

**Comment by tyrannosaurus-becks** [comment]
Closing because we don't intend to pursue this right now.
